### ISSUE TITLE
Enforce HTTPS on GH Pages?

### ISSUE THREAD

**Issue by janpio** [mitsuhiko/insta-website#6]
A co worker noticed that the website is not enforcing HTTPS and was weirded out by that. Probably just an oversight on your side or it never came up. If that is the case, you can easily fix this with this configuration setting: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site

**Comment by mitsuhiko** [comment]
Done. Thanks
